---
language: ruby
bundler_args: --without development system_tests
before_install:
  - rm Gemfile.lock || true
  - gem update --system
script: 'bundle exec rake $CHECK'
matrix:
  include:
  - rvm: 2.3.3
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes CHECK=test
  - rvm: 2.3.3
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes CHECK=rubocop
  - rvm: 2.6.6
    env: PUPPET_VERSION="~> 5.0" STRICT_VARIABLES=yes CHECK=test
  - rvm: 2.6.6
    env: PUPPET_VERSION="~> 6.0" STRICT_VARIABLES=yes CHECK=test
